require("settings")
require("plugins")
require("language")
-- require "format"
require("autocommand")
require("neoclip_setup")
require("keymaps")
require("snippets")
require("nvim-gomove")
require("tree")
require("treesitter-config")
