#! /bin/sh

killall sxhkd
sxhkd &

# timesync seems to start only after being queried ???
timedatectl timesync-status &

~/.config/bspwm/desktops.sh

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
# bspc config pointer_follows_focus       true
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config focused_border_color "#c94f6d"

bspc rule -a Thunar state=floating
bspc rule -a Nemo state=floating

bspc rule -a '*:gitk' state=floating
bspc rule -a '*:dialog' state=floating
bspc rule -a '*:gcolor3' state=floating
bspc rule -a '*:simplescreenrecorder' state=floating
bspc rule -a '*:galculator' state=floating
bspc rule -a '*:xfce4-appfinder' state=floating

bspc rule -a "*:bitwarden" state=floating rectangle=680x500 center=on
bspc rule -a "scratchterm" state=floating rectangle=1600x800+0+0 center=on

bspc config external_rules_command ~/.config/bspwm/external_rules.sh

~/.config/polybar/launch.sh &
~/.config/bspwm/setwall.sh &
~/.config/dunst/setup.sh &
# xinput set-prop "Logitech Gaming Mouse G502" "libinput Natural Scrolling Enabled" 1 &
# xinput set-prop "pointer:Logitech MX Anywhere 2S" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "pointer:Glorious Model D" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "pointer:Glorious Series One PRO Wireless" "libinput Natural Scrolling Enabled" 1 &
picom &
clipster -d &
killall udiskie
udiskie &
if [ "$HOSTNAME" = "miniarch" ]; then
  eww daemon &
  eww open sidebar &
elif [ "$HOSTNAME" = "nt-oryx" ]; then
  eww daemon &
  eww open sidebar &
  sudo system76-power profile battery
  sudo xbacklight -set 25
  sudo sys76-kb set -c purple -b 90
  # sudo dex -a &
  # disable monitor blanking and screensaver
  xset -dpms
  xset s off
fi
~/.config/bspwm/welcome.sh &
echo "rc complete"
