#!/usr/bin/env bash
id=$(xdotool search --class scratchterm)

if [ "$id" != "" ]
then
  bspc node "$id" --flag hidden -f -d $(bspc query -D -d) --follow
else
  # alacritty --class "scratchterm,scratchterm" &
  wezterm start --class "scratchterm"
fi
