#! /bin/sh

killall sxhkd
sxhkd &

# timesync seems to start only after being queried ???
timedatectl timesync-status &

~/.config/bspwm/desktops.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config click_to_focus                true
# bspc config focused_border_color "#81A1C1"
bspc config focused_border_color "#E63946"

bspc config external_rules_command ~/.config/bspwm/external_rules.sh

# bspc rule -a Gimp desktop='scratch' state=floating follow=on
bspc rule -a Chrome desktop=web
bspc rule -a Slack desktop=chat
bspc rule -a '*:zoom' desktop=chat
bspc rule -a Thunar state=floating
bspc rule -a '*:gitk' state=floating
bspc rule -a '*:dialog' state=floating
bspc rule -a '*:volume' state=floating
bspc rule -a '*:pavucontrol' state=floating rectangle=600x800+0+0 center=on
bspc rule -a "scratchterm" state=floating rectangle=1200x400+0+0 center=on

~/.config/polybar/launch.sh &
~/.config/bspwm/setwall.sh &
xinput set-prop "Logitech Gaming Mouse G502" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "pointer:Logitech MX Anywhere 2S" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "pointer:Glorious Model D" "libinput Natural Scrolling Enabled" 1 &
picom -b &
clipster -d &
killall udiskie
udiskie &
echo "rc complete"
